version: '3.8'

services:
    # Сервис PHP
    home-finder-app:
        container_name: home-finder-app
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - .:/var/www/laravel-home-finder
        networks:
            - app-network

    # Сервис Nginx
    home-finder-web:
        container_name: home-finder-web
        image: nginx:alpine
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/laravel-home-finder
        ports:
            - "80:80"
        depends_on:
            - home-finder-app
            - home-finder-db
        networks:
            - app-network

    # Сервис MySQL
    home-finder-db:
        image: mysql:8.0
        container_name: home-finder-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: home_finder
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql/
        networks:
            - app-network

# Настройки сетей
networks:
    app-network:
        driver: bridge

# Настройки томов
volumes:
    db_data:
